apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.18.0
    helm:
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            className: private
            hosts:
              core: harbor.kube.kalski.xyz
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt

        externalURL: https://harbor.kube.kalski.xyz

        existingSecretAdminPassword: harbor-admin-password
        existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD

        persistence:
          persistentVolumeClaim:
            registry:
              storageClass: local-storage
              size: 50Gi
            database:
              storageClass: local-storage
              size: 5Gi
            redis:
              storageClass: local-storage
              size: 1Gi
            trivy:
              storageClass: local-storage
              size: 5Gi
            jobservice:
              jobLog:
                storageClass: local-storage

        database:
          type: internal

        redis:
          type: internal

        trivy:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
