apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://operator.min.io
      chart: operator
      targetRevision: 7.1.1
      helm:
        values: |
          operator:
            replicaCount: 1

    - repoURL: https://operator.min.io
      chart: tenant
      targetRevision: 7.1.1
      helm:
        values: |
          tenant:
            name: minio
            configSecret:
              name: minio-env-configuration
            pools:
              - name: pool-0
                servers: 1
                volumesPerServer: 1
                size: 50Gi
                storageClassName: local-storage
            requestAutoCert: false
            exposeServices:
              console: true
              minio: true
          ingress:
            api:
              enabled: true
              ingressClassName: private
              host: minio.kube.kalski.xyz
              tls:
                - secretName: minio-api-tls
                  hosts:
                    - minio.kube.kalski.xyz
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                traefik.ingress.kubernetes.io/service.serversscheme: https
            console:
              enabled: true
              ingressClassName: private
              host: minio-console.kube.kalski.xyz
              tls:
                - secretName: minio-console-tls
                  hosts:
                    - minio-console.kube.kalski.xyz
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                traefik.ingress.kubernetes.io/service.serversscheme: https

    - repoURL: https://github.com/kahlstrm/infra.git
      targetRevision: main
      path: local-kubernetes/manifests/minio

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
