apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.18.0
    helm:
      values: |
        fullnameOverride: external-dns-mikrotik

        logLevel: debug
        logFormat: text

        interval: 5m

        sources:
          - ingress
          - service

        domainFilters:
          - kalski.xyz

        provider:
          name: webhook
          webhook:
            image:
              repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
              tag: v1.4.27
            env:
              - name: MIKROTIK_BASEURL
                valueFrom:
                  secretKeyRef:
                    name: mikrotik-credentials
                    key: MIKROTIK_BASEURL
              - name: MIKROTIK_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: mikrotik-credentials
                    key: MIKROTIK_USERNAME
              - name: MIKROTIK_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mikrotik-credentials
                    key: MIKROTIK_PASSWORD
              - name: MIKROTIK_SKIP_TLS_VERIFY
                valueFrom:
                  secretKeyRef:
                    name: mikrotik-credentials
                    key: MIKROTIK_SKIP_TLS_VERIFY
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8888
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /readyz
                port: 8888
              initialDelaySeconds: 10
              timeoutSeconds: 5

        policy: sync

        extraArgs:
          - --ignore-ingress-tls-spec

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
