apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      #     With Helm v3, CRDs created by this chart are not updated by default and should be manually updated. Consult also the Helm Documentation on CRDs.
      #     CRDs update lead to a major version bump. The Chart's appVersion refers to the prometheus-operator's version with matching CRDs.
      targetRevision: 79.7.1
      helm:
        values: |
          grafana:
            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - grafana.kube.kalski.xyz
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
              tls:
                - secretName: grafana-tls
                  hosts:
                    - grafana.kube.kalski.xyz
            persistence:
              enabled: true
              storageClassName: local-storage
              size: 10Gi

          prometheus:
            prometheusSpec:
              retention: 30d
              serviceMonitorNamespaceSelector:
                matchNames:
                  - monitoring
                  - monitoring-privileged
              podMonitorNamespaceSelector:
                matchNames:
                  - monitoring
                  - monitoring-privileged
              serviceMonitorSelector:
                matchLabels:
                  app.kubernetes.io/name: node-exporter
              podMonitorSelector:
                matchLabels:
                  app.kubernetes.io/name: node-exporter
              serviceMonitorSelectorNilUsesHelmValues: false
              podMonitorSelectorNilUsesHelmValues: false
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: local-storage
                    resources:
                      requests:
                        storage: 40Gi

          alertmanager:
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: local-storage
                    resources:
                      requests:
                        storage: 5Gi

          prometheus-node-exporter:
            namespaceOverride: monitoring-privileged
    - repoURL: https://github.com/kahlstrm/infra.git
      targetRevision: main
      path: local-kubernetes/manifests/monitoring-privileged

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
