apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      #     With Helm v3, CRDs created by this chart are not updated by default and should be manually updated. Consult also the Helm Documentation on CRDs.
      #     CRDs update lead to a major version bump. The Chart's appVersion refers to the prometheus-operator's version with matching CRDs.
      targetRevision: 79.7.1
      helm:
        values: |
          grafana:
            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - grafana.kube.kalski.xyz
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
              tls:
                - secretName: grafana-tls
                  hosts:
                    - grafana.kube.kalski.xyz
            serviceMonitor:
              enabled: true
              labels:
                release: observability
              interval: 30s
              scrapeTimeout: 10s
              path: /metrics
            persistence:
              enabled: true
              storageClassName: local-storage
              size: 10Gi
            initChownData:
              enabled: false
            podSecurityContext:
              runAsUser: 472
              runAsGroup: 472
              fsGroup: 472
              fsGroupChangePolicy: OnRootMismatch

          prometheus:
            prometheusSpec:
              retention: 30d
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: local-storage
                    resources:
                      requests:
                        storage: 40Gi

          alertmanager:
            alertmanagerSpec:
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: local-storage
                    resources:
                      requests:
                        storage: 5Gi

          prometheus-node-exporter:
            namespaceOverride: monitoring-privileged

          kubeEtcd:
            enabled: true
            service:
              selector:
                k8s-app: kube-controller-manager # hostNetwork pod gives node IPs without hardcoding
            serviceMonitor:
              scheme: http
              relabelings:
                - sourceLabels: [__meta_kubernetes_pod_node_name]
                  targetLabel: nodename
                  action: replace
              metricRelabelings:
                - action: labeldrop
                  regex: pod
    - repoURL: https://github.com/kahlstrm/infra.git
      targetRevision: main
      path: local-kubernetes/manifests/monitoring-privileged

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
