apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docsight
resources:
- resources.yaml
- prometheusrule.yaml
- ingress.yaml
configMapGenerator:
- name: docsight-scripts
  files:
  - scripts/bootstrap.py
images:
- name: docsight
  newName: ghcr.io/kahlstrm/docsight
  newTag: main
  digest: sha256:921e86d616b7c4a91583fc2d5b1212da2df6a8543687580b7e81a00b2fc9fb47
