apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docsight
resources:
- resources.yaml
- prometheusrule.yaml
- ingress.yaml
configMapGenerator:
- name: docsight-scripts
  files:
  - scripts/bootstrap.py
images:
- name: docsight
  newName: ghcr.io/kahlstrm/docsight
  newTag: main
  digest: sha256:9aa086efee905ec1fae57e1f5777a73a4c104947527354db5ef234fb7472c9d2
